# Generated by Django 4.2.7 on 2023-12-07 09:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lostacos', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Buyer',
        ),
        migrations.AlterModelManagers(
            name='buyer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
