# Generated by Django 4.2.7 on 2023-12-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostacos', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostacos.category'),
        ),
    ]
