# Generated by Django 4.2.7 on 2023-12-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostacos', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='stock_quantity',
        ),
    ]
